name: CI

on:
  pull_request:
    branches:
      - dev
      - qa

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle (show all warnings)
        run: ./gradlew build --warning-mode all
      - name: Run tests
        run: ./gradlew test --warning-mode all
